;;; HNSW Spike - Distance Functions
(in-package :hnsw-spike)

(defun cosine-distance (v1 v2)
  (declare (type (simple-array single-float (*)) v1 v2)
           (optimize (speed 3) (space 0) (debug 0)))
  (let* ((dot 0.0)
         (norm1 0.0)
         (norm2 0.0)
         (len (length v1)))
    (declare (type fixnum len)
             (type single-float dot norm1 norm2))
    (dotimes (i len)
      (let ((a (aref v1 i))
            (b (aref v2 i)))
        (incf dot (* a b))
        (incf norm1 (* a a))
        (incf norm2 (* b b))))
    (let ((norms (sqrt (* norm1 norm2))))
      (if (zerop norms)
          1.0
          (- 1.0 (/ dot norms))))))

(defun l2-distance (v1 v2)
  (declare (type (simple-array single-float (*)) v1 v2)
           (optimize (speed 3) (space 0) (debug 0)))
  (let ((sum 0.0)
        (len (length v1)))
    (dotimes (i len)
      (let ((diff (- (aref v1 i) (aref v2 i))))
        (incf sum (* diff diff))))
    (sqrt sum)))

(defun dot-distance (v1 v2)
  (declare (type (simple-array single-float (*)) v1 v2)
           (optimize (speed 3) (space 0) (debug 0)))
  (let ((sum 0.0)
        (len (length v1)))
    (dotimes (i len)
      (incf sum (* (aref v1 i) (aref v2 i))))
    (- sum)))
