;;; HNSW Spike - Heap Functions
(in-package :hnsw-spike)

(defun heap-push! (heap item score-key)
  (vector-push-extend item heap)
  (let ((i (1- (length heap))))
    (loop while (> i 0)
          for parent = (floor (1- i) 2)
          when (<= (funcall score-key (aref heap parent))
                   (funcall score-key (aref heap i)))
          do (return)
          do (rotatef (aref heap i) (aref heap parent))
             (setf i parent))))

(defun heap-pop! (heap score-key)
  (when (zerop (length heap))
    (return-from heap-pop! nil))
  (let ((result (aref heap 0))
        (last (vector-pop heap)))
    (when (zerop (length heap))
      (return-from heap-pop! result))
    (setf (aref heap 0) last)
    (let ((i 0))
      (tagbody
       loop-start
         (let* ((left (1+ (* i 2)))
                (right (1+ left))
                (smallest i))
           (when (and (< left (length heap))
                      (< (funcall score-key (aref heap left))
                         (funcall score-key (aref heap smallest))))
             (setf smallest left))
           (when (and (< right (length heap))
                      (< (funcall score-key (aref heap right))
                         (funcall score-key (aref heap smallest))))
             (setf smallest right))
           (when (= smallest i)
             (go loop-end))
           (rotatef (aref heap i) (aref heap smallest))
           (setf i smallest)
           (go loop-start))
       loop-end)
      result)))